"""add unique constraint and indexes to production

Revision ID: 166536ceed4d
Revises: 1d6b39d34313
Create Date: 2026-07-03 16:05:52.842790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166536ceed4d'
down_revision: Union[str, Sequence[str], None] = '1d6b39d34313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_id'), table_name='production')
    op.create_index(op.f('ix_production_month'), 'production', ['month'], unique=False)
    op.create_index(op.f('ix_production_uwi'), 'production', ['uwi'], unique=False)
    op.create_unique_constraint(None, 'production', ['uwi', 'month'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production', type_='unique')
    op.drop_index(op.f('ix_production_uwi'), table_name='production')
    op.drop_index(op.f('ix_production_month'), table_name='production')
    op.create_index(op.f('ix_production_id'), 'production', ['id'], unique=False)
    # ### end Alembic commands ###
