"""fix production id autoincrement

Revision ID: 1d6b39d34313
Revises: 50c91c7c5600
Create Date: 2026-06-03 16:58:18.066937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6b39d34313'
down_revision: Union[str, Sequence[str], None] = '50c91c7c5600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('production',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('uwi', sa.String(), nullable=True),
        sa.Column('oil', sa.Float(), nullable=False),
        sa.Column('water', sa.Float(), nullable=False),
        sa.Column('gas', sa.Float(), nullable=False),
        sa.Column('month', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['uwi'], ['wells.uwi'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_id'), 'production', ['id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
