"""create wells production forecast tables

Revision ID: d6b564a93a46
Revises: 
Create Date: 2026-05-28 17:03:17.575754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b564a93a46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wells',
    sa.Column('uwi', sa.String(), nullable=False),
    sa.Column('licensee', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('uwi')
    )
    op.create_index(op.f('ix_wells_uwi'), 'wells', ['uwi'], unique=False)
    op.create_table('forecast',
    sa.Column('uwi', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qi', sa.Float(), nullable=False),
    sa.Column('di', sa.Float(), nullable=False),
    sa.Column('b', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uwi'], ['wells.uwi'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_id'), 'forecast', ['id'], unique=False)
    op.create_table('production',
    sa.Column('uwi', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('oil', sa.Float(), nullable=False),
    sa.Column('water', sa.Float(), nullable=False),
    sa.Column('gas', sa.Float(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uwi'], ['wells.uwi'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_id'), 'production', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_id'), table_name='production')
    op.drop_table('production')
    op.drop_index(op.f('ix_forecast_id'), table_name='forecast')
    op.drop_table('forecast')
    op.drop_index(op.f('ix_wells_uwi'), table_name='wells')
    op.drop_table('wells')
    # ### end Alembic commands ###
